on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    types: [ "review_requested", "ready_for_review" ]
  workflow_dispatch:
name: Flatpak
permissions:
  id-token: write
  contents: read
jobs:
  gnome-flatpak:
    name: "Flatpak"
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.user.login != 'weblate' }}
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-45
      options: --privileged
    strategy:
      matrix:
        arch: [x86_64]
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: flatpak/flatpak-github-actions/flatpak-builder@v6.3
        with:
          bundle: io.github.amit9838.weather.flatpak
          manifest-path: io.github.amit9838.weather.json
          cache-key: flatpak-builder-${{ github.sha }}
          arch: ${{ matrix.arch }}
          restore-cache: true
